### ISSUE TITLE
Incorporate remaining USWDS classes into form wizard template(s)

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#61]
In particular:
* `usa-input-error`
* `usa-input-error-label`
* `help-text usa-form-hint`
* `usa-input-error-message` (and `role="alert"`)

Previously, this was handled this way:
```
    {% for field in form %}
      {% if field.errors %}<div class="usa-input-error">{% endif %}
        <label for="{{ field|id }}" {% if field.errors %}class="usa-input-error-label"{% endif %}>
          {{ field.label }}:
        </label>
        {% if field.help_text %}<div class="help-text usa-form-hint">{{ field.help_text }}</div>{% endif %}
        {% for error in field.errors %}
          <span class="usa-input-error-message" role="alert">{{ error }}</span>
        {% endfor %}
        {% widget field %}
      {% if field.errors %}</div>{% endif %}
    {% endfor %}
```

`fafsa_form.html` is currently the relevant file.

**Comment by fureigh** [comment]
@micahsaul @donjo (How) was this resolved in the last round? I don't see evidence of the USWDS classes in the codebase, but please point me to them if I'm missing something.

**Comment by fureigh** [comment]
Either way, considering that our focus isn't testing the overall form UX, I'm inclined to deprioritize this.

**Comment by donjo** [comment]
For the help text I ended up using the tooltip and tooltip text pattern that the USWDS documentation site uses (not a part of the USWDS package, I just used that CSS) to create the '?' that you can hover over for more information. Is there an example on the standards site of what the `help-text usa-form-hint` looks like? I was looking for that and only chose this alternate solution because I couldn't find the built-in method. 

Then error messages were never fully implemented because validation was turned off for the sake of testing. However, that if we do turn that on for the next prototype, I'd recommend that we still do this.

**Comment by fureigh** [comment]
Thanks for the info, @donjo! I've been leaving most validation out so that people can skip questions and page through during the testing sessions. Assuming that still meets our needs, I don't think we need to make fields required, etc.

Here's what I see in `uswds.css` for `usa-form-hint`:

> .usa-form-hint {
  color: #757575;
  font-family: "Source Sans Pro", "Helvetica Neue", "Helvetica", "Roboto", "Arial", sans-serif;
  margin-bottom: 0;
}

**Comment by fureigh** [comment]
(For further context on intentionally leaving out most validation, see #66.)

**Comment by porta-antiporta** [comment]
closing given project is done.  can reopen if we start building other prototypes.
